Vagrant.configure("2") do |config|
	# config.vm.box = "bento/ubuntu-20.04"
	config.vm.box = "ubuntu/focal64"
	config.vm.provision :shell, path: "bootstrap.sh"
	config.vm.network :forwarded_port, guest: 3000, host: 3000
	config.vm.network :forwarded_port, guest: 27017, host: 27018
end
